// Super temp. remove when done with skills
const skillsWithDetails = {
    "abyss_knight": true,
    "ancients_hand": true,
    "angel_of_death": true,
    "apocalypse": true,
    "antimass": true,
    "arcane_swarm": true,
    "arcane_torrent": true,
    "arrow_swarm": true,
    "atmg_sentry": true,
    "avalanche": true,
    "balefire": true,
    "bane": true,
    "banish": true,
    "barrage": true,
    "bend_the_shadows": true,
    "black_lotus_strike": true,
    "bladestorm": true,
    "blink": true,
    "bloodstar": true,
    "bloodstorm": true,
    "blood_fury": true,
    "chaos_nova": true,
    "deathgaze": true,
    "death_pact": true,
    "devouring_cloud": true,
    "earthquake": true,
    "famine": true,
    "mind_control": true,
    "orb_of_annihilation": true,
    "remorseless_winter": true,
    "resurgence": true,
    "sacrifices": true,
    "scepter_mastery": true,
    "town_portal": true,
    "treewarden_morph": true,
    "let_me_solo_him": true,
    "clear_mind": true,
    "exorcism": true,
    "void_armor": true,
    "thorn_field": true,
    "mooncall": true,
    "embalming": true,
    "disintegrate": true,
    "demonic_speed": true,
    "death_ward": true,
    "champions_of_the_sun": true,
    "bloodlust": true,
    "amatoxin": true,
    "arachnomancy": true,
    "broadside": true,
    "charged_strike": true,
    "cherubim": true,
    "churel": true,
    "colosseum": true,
    "cone_of_cold": true,
    "crucify": true,
    "death_ripple": true,
    "flameburst_shot": true,
    "shatter_the_flesh": true,
    "split_arrow": true,
    "dark_power": true,
    "defender_spirit": true,
    "disco_inferno": true,
    "diseased_cattle": true,
    "divine_judgement": true,
    "catapult_show": true,
    "dream_eater": true,
    "ecstating_frenzy": true,
    "ember_spirit": true,
    "trinity_nova": true,
    "elemental_totem": true,
    "emerald_prison": true,
    "impale": true,
    "feral_strike": true,
    "pentagram": true,
    "firedance": true,
    "path_of_flames": true,
    "nova_charge": true,
    "lightning_arena": true,
    "hive": true,
    "frostclaw_totem": true,
    "frigid_nova": true,
    "fortress": true,
    "forked_lightning": true,
    "flash": true,
    "flamestrike": true,
    "flamefront": true,
    "fireheart_totem": true
}

let showDetailedOnly = false;

$.fn.dataTable.ext.search.push(function(settings, data, dataIndex) {
    if (!showDetailedOnly) return true;

    const row = settings.aoData[dataIndex].nTr;
    return $(row).attr("data-has-page") === "true";
});